### ISSUE TITLE
Desarrollar en Angular la funcionalidad del dashboard y conectarla con la API

### ISSUE THREAD

**Issue by ghost** [BioniX-es/Bionix-Frontend#2]
Utilizaremos docker para separar el servidor web con el front-end del resto de la API y los servicios. Intentaremos separar los servicios de la base de datos.
Links de utilidad:
- https://docs.docker.com/get-started/
- https://docs.docker.com/engine/reference/builder/ 
- https://hub.docker.com/r/bankmonitor/spring-boot/
- https://hub.docker.com/_/mysql/ 
- https://docs.docker.com/glossary/?term=volume (útil para la base de datos)

**Comment by christianbegines** [comment]
vale es muy sencilo montar el docker para una app de anuglar, solo hay que coger el ts compilado en js, y meterlo en el html hajajaj y voilá

**Comment by ajaniramon** [comment]
Ya está hecho. En jenkins tenéis las builds de despliegue.
